builds:
  - binary: openio.plugin
    main: openio.plugin.go
    flags: "-gccgoflags '-static'"
    goos:
      - linux
    goarch:
      - amd64
  - binary: zookeeper.plugin
    main: zookeeper.plugin.go
    flags: "-gccgoflags '-static'"
    goos:
      - linux
    goarch:
      - amd64
  - binary: container.plugin
    main: container.plugin.go
    flags: "-gccgoflags '-static'"
    goos:
      - linux
    goarch:
      - amd64

archive:
  wrap_in_directory: false
  name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}"

release:
  github:
    owner: vdombrovski
    name: openio-netdata
  draft: true
  prerelease: true
  name_template: "v{{.Version}}"

nfpm:
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Env.RELEASE }}.{{ .Arch }}"
  replacements:
    amd64: x86_64

  vendor: OpenIO
  homepage: https://openio.io/
  maintainer: Vladimir DOMBROVSKI <vladimir@openio.io>
  license: Apache 2.0
  description: OpenIO collectors for netdata
  formats:
    - deb
    - rpm
  dependencies:
    - netdata
  bindir: /usr/lib/netdata/plugins.d/
